# Generated by Django 4.1.6 on 2023-04-04 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_district_division_parish_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=False)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.village')),
            ],
            options={
                'verbose_name': 'street',
                'verbose_name_plural': 'street',
            },
        ),
    ]
